### ISSUE TITLE
Check Version

### ISSUE THREAD

**Issue by Atorcha** [shiroichiheisen/Esp32-Web-Update#1]
Hello.

Could you add the option to check the version of update?
 In this way if a new version, then update, else not.

Thanks for you work  and regards

**Comment by imoiseev** [comment]
You need to save the BUILD variable somewhere after the update. For example, you updated and saved BUILD=4440.
On the server, create a file that will store the number of the last BUILD of the firmware loaded on the server (.bin)

Then you simply compare the number, if your BUILD is less than what is on the server - just update

**Comment by shiroichiheisen** [comment]
Question answered by IMOISEEV
